BACK = "BackButton"
CANCEL_WHITE = "CancelButtonWhite"
CHALLENGE_BLACK = "ChallengeBlack"
CHALLENGE_BLUE = "ChallengeButtonBlue"
CHALLENGE_WHITE = "ChallengeButtonWhite"
COLLECT_WHITE = "CollectButtonWhite"
CONTINUE_BLUE = "ContinueButtonBlue"
CONTINUE_WHITE = "ContinueButtonWhite"
DAILY_CHALLENGES = "DailyChallengesButton"
LEVEL_BLACK = "LevelBlack"
LEVEL_BLUE = "LevelButtonBlue"
LEVEL_WHITE = "LevelButtonWhite"
MAIN = "MainButton"
MAIN_BLUE = "MainButtonBlue"
MY_COLLECTION_WHITE = "MyCollectionButtonWhite"
NONOGRAM_TITLE = "NonogramTitle"
PLAY_BLUE = "PlayButtonBlue"
PLAY_WHITE = "PlayButtonWhite"
PREVIOUS_MONTH_BLUE = "PreviousMonthButtonBlue"
RESTART_WHITE = "RestartLevelButtonWhite"

ASSET_IMAGES = [BACK, CANCEL_WHITE, CHALLENGE_BLACK, CHALLENGE_BLUE, CHALLENGE_WHITE, COLLECT_WHITE, CONTINUE_BLUE, 
                CONTINUE_WHITE, DAILY_CHALLENGES, LEVEL_BLACK, LEVEL_BLUE, LEVEL_WHITE, MAIN, MAIN_BLUE, MY_COLLECTION_WHITE,
                 NONOGRAM_TITLE, PLAY_BLUE, PLAY_WHITE, PREVIOUS_MONTH_BLUE, RESTART_WHITE]

DEFAULT_SCREEN_WIDTH = 1131
DEFAULT_SCREEN_HEIGHT = 2012